// 使用 proto3 语法

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.5
// source: sdk_client/clientserver.proto

// proto 包名

package csv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MsgType int32

const (
	MsgType_MsgID_MsgHeartBeat MsgType = 0 // 心跳
	MsgType_MsgID_MsgLoginReq  MsgType = 1 // 登录
	MsgType_MsgID_MsgLoginResp MsgType = 2 // 登录响应
	MsgType_MsgID_MsgQueueInfo MsgType = 3 // 排队信息
)

// Enum value maps for MsgType.
var (
	MsgType_name = map[int32]string{
		0: "MsgID_MsgHeartBeat",
		1: "MsgID_MsgLoginReq",
		2: "MsgID_MsgLoginResp",
		3: "MsgID_MsgQueueInfo",
	}
	MsgType_value = map[string]int32{
		"MsgID_MsgHeartBeat": 0,
		"MsgID_MsgLoginReq":  1,
		"MsgID_MsgLoginResp": 2,
		"MsgID_MsgQueueInfo": 3,
	}
)

func (x MsgType) Enum() *MsgType {
	p := new(MsgType)
	*p = x
	return p
}

func (x MsgType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MsgType) Descriptor() protoreflect.EnumDescriptor {
	return file_sdk_client_clientserver_proto_enumTypes[0].Descriptor()
}

func (MsgType) Type() protoreflect.EnumType {
	return &file_sdk_client_clientserver_proto_enumTypes[0]
}

func (x MsgType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MsgType.Descriptor instead.
func (MsgType) EnumDescriptor() ([]byte, []int) {
	return file_sdk_client_clientserver_proto_rawDescGZIP(), []int{0}
}

// ws客户端和账服之间消息通信协议
type Message struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MsgID MsgType `protobuf:"varint,1,opt,name=msgID,proto3,enum=api.clientserver.v1.MsgType" json:"msgID,omitempty"` // 消息类型
	Data  []byte  `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`                                     // 消息数据
}

func (x *Message) Reset() {
	*x = Message{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sdk_client_clientserver_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message) ProtoMessage() {}

func (x *Message) ProtoReflect() protoreflect.Message {
	mi := &file_sdk_client_clientserver_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message.ProtoReflect.Descriptor instead.
func (*Message) Descriptor() ([]byte, []int) {
	return file_sdk_client_clientserver_proto_rawDescGZIP(), []int{0}
}

func (x *Message) GetMsgID() MsgType {
	if x != nil {
		return x.MsgID
	}
	return MsgType_MsgID_MsgHeartBeat
}

func (x *Message) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

// 心跳
type MsgHeartBeat struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserID uint64 `protobuf:"varint,1,opt,name=userID,proto3" json:"userID,omitempty"` // 账号id
}

func (x *MsgHeartBeat) Reset() {
	*x = MsgHeartBeat{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sdk_client_clientserver_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MsgHeartBeat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgHeartBeat) ProtoMessage() {}

func (x *MsgHeartBeat) ProtoReflect() protoreflect.Message {
	mi := &file_sdk_client_clientserver_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgHeartBeat.ProtoReflect.Descriptor instead.
func (*MsgHeartBeat) Descriptor() ([]byte, []int) {
	return file_sdk_client_clientserver_proto_rawDescGZIP(), []int{1}
}

func (x *MsgHeartBeat) GetUserID() uint64 {
	if x != nil {
		return x.UserID
	}
	return 0
}

// 登录请求
type MsgLoginReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AppID         string `protobuf:"bytes,1,opt,name=appID,proto3" json:"appID,omitempty"`                 // sdk应用id
	PlatformID    uint32 `protobuf:"varint,2,opt,name=platformID,proto3" json:"platformID,omitempty"`      // sdk平台id
	AccountID     string `protobuf:"bytes,3,opt,name=accountID,proto3" json:"accountID,omitempty"`         // sdk账号id
	SessionID     string `protobuf:"bytes,4,opt,name=sessionID,proto3" json:"sessionID,omitempty"`         // sdk会话id
	SessionSecret string `protobuf:"bytes,5,opt,name=sessionSecret,proto3" json:"sessionSecret,omitempty"` // sdk会话密钥
	ClientType    uint32 `protobuf:"varint,6,opt,name=clientType,proto3" json:"clientType,omitempty"`      // 客户端类型;0-pc；1-linux；2-mac；3-ios；4-android；5-windows
	ClientVersion string `protobuf:"bytes,7,opt,name=clientVersion,proto3" json:"clientVersion,omitempty"` // 客户端版本号
	RegionID      uint32 `protobuf:"varint,8,opt,name=regionID,proto3" json:"regionID,omitempty"`          // 区id
	ServerID      uint32 `protobuf:"varint,9,opt,name=serverID,proto3" json:"serverID,omitempty"`          // 服务器id,此区服id等价于slg中的worldID
}

func (x *MsgLoginReq) Reset() {
	*x = MsgLoginReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sdk_client_clientserver_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MsgLoginReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgLoginReq) ProtoMessage() {}

func (x *MsgLoginReq) ProtoReflect() protoreflect.Message {
	mi := &file_sdk_client_clientserver_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgLoginReq.ProtoReflect.Descriptor instead.
func (*MsgLoginReq) Descriptor() ([]byte, []int) {
	return file_sdk_client_clientserver_proto_rawDescGZIP(), []int{2}
}

func (x *MsgLoginReq) GetAppID() string {
	if x != nil {
		return x.AppID
	}
	return ""
}

func (x *MsgLoginReq) GetPlatformID() uint32 {
	if x != nil {
		return x.PlatformID
	}
	return 0
}

func (x *MsgLoginReq) GetAccountID() string {
	if x != nil {
		return x.AccountID
	}
	return ""
}

func (x *MsgLoginReq) GetSessionID() string {
	if x != nil {
		return x.SessionID
	}
	return ""
}

func (x *MsgLoginReq) GetSessionSecret() string {
	if x != nil {
		return x.SessionSecret
	}
	return ""
}

func (x *MsgLoginReq) GetClientType() uint32 {
	if x != nil {
		return x.ClientType
	}
	return 0
}

func (x *MsgLoginReq) GetClientVersion() string {
	if x != nil {
		return x.ClientVersion
	}
	return ""
}

func (x *MsgLoginReq) GetRegionID() uint32 {
	if x != nil {
		return x.RegionID
	}
	return 0
}

func (x *MsgLoginReq) GetServerID() uint32 {
	if x != nil {
		return x.ServerID
	}
	return 0
}

// 登录响应
type MsgLoginResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code         uint32 `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`                 // 登录结果，0-成功；1-失败
	Msg          string `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`                    // 登录结果描述
	UserID       uint64 `protobuf:"varint,3,opt,name=userID,proto3" json:"userID,omitempty"`             // 账服id
	Token        string `protobuf:"bytes,4,opt,name=token,proto3" json:"token,omitempty"`                // token
	ServerIP     string `protobuf:"bytes,5,opt,name=serverIP,proto3" json:"serverIP,omitempty"`          // 服务器ip
	ServerPort   uint32 `protobuf:"varint,6,opt,name=serverPort,proto3" json:"serverPort,omitempty"`     // 服务器端口
	CustomInfo   string `protobuf:"bytes,7,opt,name=customInfo,proto3" json:"customInfo,omitempty"`      // 自定义信息
	DeadlineTime int64  `protobuf:"varint,8,opt,name=deadlineTime,proto3" json:"deadlineTime,omitempty"` // code=12时才有效，封号截止时间，0为永久封号
}

func (x *MsgLoginResp) Reset() {
	*x = MsgLoginResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sdk_client_clientserver_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MsgLoginResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgLoginResp) ProtoMessage() {}

func (x *MsgLoginResp) ProtoReflect() protoreflect.Message {
	mi := &file_sdk_client_clientserver_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgLoginResp.ProtoReflect.Descriptor instead.
func (*MsgLoginResp) Descriptor() ([]byte, []int) {
	return file_sdk_client_clientserver_proto_rawDescGZIP(), []int{3}
}

func (x *MsgLoginResp) GetCode() uint32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *MsgLoginResp) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *MsgLoginResp) GetUserID() uint64 {
	if x != nil {
		return x.UserID
	}
	return 0
}

func (x *MsgLoginResp) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *MsgLoginResp) GetServerIP() string {
	if x != nil {
		return x.ServerIP
	}
	return ""
}

func (x *MsgLoginResp) GetServerPort() uint32 {
	if x != nil {
		return x.ServerPort
	}
	return 0
}

func (x *MsgLoginResp) GetCustomInfo() string {
	if x != nil {
		return x.CustomInfo
	}
	return ""
}

func (x *MsgLoginResp) GetDeadlineTime() int64 {
	if x != nil {
		return x.DeadlineTime
	}
	return 0
}

// 排队信息
type MsgQueueInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserID   uint64 `protobuf:"varint,1,opt,name=userID,proto3" json:"userID,omitempty"`     // 账服id
	Position uint32 `protobuf:"varint,2,opt,name=position,proto3" json:"position,omitempty"` // 排队位置
	Speed    uint32 `protobuf:"varint,3,opt,name=speed,proto3" json:"speed,omitempty"`       // 排队速度,预估，单位：人/分钟
}

func (x *MsgQueueInfo) Reset() {
	*x = MsgQueueInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sdk_client_clientserver_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MsgQueueInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgQueueInfo) ProtoMessage() {}

func (x *MsgQueueInfo) ProtoReflect() protoreflect.Message {
	mi := &file_sdk_client_clientserver_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgQueueInfo.ProtoReflect.Descriptor instead.
func (*MsgQueueInfo) Descriptor() ([]byte, []int) {
	return file_sdk_client_clientserver_proto_rawDescGZIP(), []int{4}
}

func (x *MsgQueueInfo) GetUserID() uint64 {
	if x != nil {
		return x.UserID
	}
	return 0
}

func (x *MsgQueueInfo) GetPosition() uint32 {
	if x != nil {
		return x.Position
	}
	return 0
}

func (x *MsgQueueInfo) GetSpeed() uint32 {
	if x != nil {
		return x.Speed
	}
	return 0
}

var File_sdk_client_clientserver_proto protoreflect.FileDescriptor

var file_sdk_client_clientserver_proto_rawDesc = []byte{
	0x0a, 0x1d, 0x73, 0x64, 0x6b, 0x5f, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x2f, 0x63, 0x6c, 0x69,
	0x65, 0x6e, 0x74, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x13, 0x61, 0x70, 0x69, 0x2e, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x73, 0x65, 0x72, 0x76, 0x65,
	0x72, 0x2e, 0x76, 0x31, 0x22, 0x51, 0x0a, 0x07, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12,
	0x32, 0x0a, 0x05, 0x6d, 0x73, 0x67, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x1c,
	0x2e, 0x61, 0x70, 0x69, 0x2e, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x73, 0x65, 0x72, 0x76, 0x65,
	0x72, 0x2e, 0x76, 0x31, 0x2e, 0x4d, 0x73, 0x67, 0x54, 0x79, 0x70, 0x65, 0x52, 0x05, 0x6d, 0x73,
	0x67, 0x49, 0x44, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0c, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x26, 0x0a, 0x0c, 0x4d, 0x73, 0x67, 0x48, 0x65,
	0x61, 0x72, 0x74, 0x42, 0x65, 0x61, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49,
	0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x44, 0x22,
	0xa3, 0x02, 0x0a, 0x0b, 0x4d, 0x73, 0x67, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x52, 0x65, 0x71, 0x12,
	0x14, 0x0a, 0x05, 0x61, 0x70, 0x70, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05,
	0x61, 0x70, 0x70, 0x49, 0x44, 0x12, 0x1e, 0x0a, 0x0a, 0x70, 0x6c, 0x61, 0x74, 0x66, 0x6f, 0x72,
	0x6d, 0x49, 0x44, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0a, 0x70, 0x6c, 0x61, 0x74, 0x66,
	0x6f, 0x72, 0x6d, 0x49, 0x44, 0x12, 0x1c, 0x0a, 0x09, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74,
	0x49, 0x44, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e,
	0x74, 0x49, 0x44, 0x12, 0x1c, 0x0a, 0x09, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x49, 0x44,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x49,
	0x44, 0x12, 0x24, 0x0a, 0x0d, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x53, 0x65, 0x63, 0x72,
	0x65, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f,
	0x6e, 0x53, 0x65, 0x63, 0x72, 0x65, 0x74, 0x12, 0x1e, 0x0a, 0x0a, 0x63, 0x6c, 0x69, 0x65, 0x6e,
	0x74, 0x54, 0x79, 0x70, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0a, 0x63, 0x6c, 0x69,
	0x65, 0x6e, 0x74, 0x54, 0x79, 0x70, 0x65, 0x12, 0x24, 0x0a, 0x0d, 0x63, 0x6c, 0x69, 0x65, 0x6e,
	0x74, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d,
	0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x1a, 0x0a,
	0x08, 0x72, 0x65, 0x67, 0x69, 0x6f, 0x6e, 0x49, 0x44, 0x18, 0x08, 0x20, 0x01, 0x28, 0x0d, 0x52,
	0x08, 0x72, 0x65, 0x67, 0x69, 0x6f, 0x6e, 0x49, 0x44, 0x12, 0x1a, 0x0a, 0x08, 0x73, 0x65, 0x72,
	0x76, 0x65, 0x72, 0x49, 0x44, 0x18, 0x09, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x08, 0x73, 0x65, 0x72,
	0x76, 0x65, 0x72, 0x49, 0x44, 0x22, 0xe2, 0x01, 0x0a, 0x0c, 0x4d, 0x73, 0x67, 0x4c, 0x6f, 0x67,
	0x69, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0d, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x73,
	0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6d, 0x73, 0x67, 0x12, 0x16, 0x0a, 0x06,
	0x75, 0x73, 0x65, 0x72, 0x49, 0x44, 0x18, 0x03, 0x20, 0x01, 0x28, 0x04, 0x52, 0x06, 0x75, 0x73,
	0x65, 0x72, 0x49, 0x44, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x1a, 0x0a, 0x08, 0x73, 0x65,
	0x72, 0x76, 0x65, 0x72, 0x49, 0x50, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x73, 0x65,
	0x72, 0x76, 0x65, 0x72, 0x49, 0x50, 0x12, 0x1e, 0x0a, 0x0a, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72,
	0x50, 0x6f, 0x72, 0x74, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0a, 0x73, 0x65, 0x72, 0x76,
	0x65, 0x72, 0x50, 0x6f, 0x72, 0x74, 0x12, 0x1e, 0x0a, 0x0a, 0x63, 0x75, 0x73, 0x74, 0x6f, 0x6d,
	0x49, 0x6e, 0x66, 0x6f, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x63, 0x75, 0x73, 0x74,
	0x6f, 0x6d, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x22, 0x0a, 0x0c, 0x64, 0x65, 0x61, 0x64, 0x6c, 0x69,
	0x6e, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x08, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0c, 0x64, 0x65,
	0x61, 0x64, 0x6c, 0x69, 0x6e, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x22, 0x58, 0x0a, 0x0c, 0x4d, 0x73,
	0x67, 0x51, 0x75, 0x65, 0x75, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x16, 0x0a, 0x06, 0x75, 0x73,
	0x65, 0x72, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72,
	0x49, 0x44, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0d, 0x52, 0x08, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x14,
	0x0a, 0x05, 0x73, 0x70, 0x65, 0x65, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x05, 0x73,
	0x70, 0x65, 0x65, 0x64, 0x2a, 0x68, 0x0a, 0x07, 0x4d, 0x73, 0x67, 0x54, 0x79, 0x70, 0x65, 0x12,
	0x16, 0x0a, 0x12, 0x4d, 0x73, 0x67, 0x49, 0x44, 0x5f, 0x4d, 0x73, 0x67, 0x48, 0x65, 0x61, 0x72,
	0x74, 0x42, 0x65, 0x61, 0x74, 0x10, 0x00, 0x12, 0x15, 0x0a, 0x11, 0x4d, 0x73, 0x67, 0x49, 0x44,
	0x5f, 0x4d, 0x73, 0x67, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x52, 0x65, 0x71, 0x10, 0x01, 0x12, 0x16,
	0x0a, 0x12, 0x4d, 0x73, 0x67, 0x49, 0x44, 0x5f, 0x4d, 0x73, 0x67, 0x4c, 0x6f, 0x67, 0x69, 0x6e,
	0x52, 0x65, 0x73, 0x70, 0x10, 0x02, 0x12, 0x16, 0x0a, 0x12, 0x4d, 0x73, 0x67, 0x49, 0x44, 0x5f,
	0x4d, 0x73, 0x67, 0x51, 0x75, 0x65, 0x75, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x10, 0x03, 0x42, 0x45,
	0x5a, 0x43, 0x67, 0x69, 0x74, 0x2e, 0x6e, 0x64, 0x2e, 0x63, 0x6f, 0x6d, 0x2e, 0x63, 0x6e, 0x2f,
	0x67, 0x61, 0x6d, 0x65, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x2f, 0x67, 0x61, 0x6d, 0x65,
	0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x2d, 0x67, 0x72, 0x70, 0x63, 0x2f, 0x61, 0x70, 0x69,
	0x2f, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2f, 0x76, 0x31,
	0x3b, 0x63, 0x73, 0x76, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_sdk_client_clientserver_proto_rawDescOnce sync.Once
	file_sdk_client_clientserver_proto_rawDescData = file_sdk_client_clientserver_proto_rawDesc
)

func file_sdk_client_clientserver_proto_rawDescGZIP() []byte {
	file_sdk_client_clientserver_proto_rawDescOnce.Do(func() {
		file_sdk_client_clientserver_proto_rawDescData = protoimpl.X.CompressGZIP(file_sdk_client_clientserver_proto_rawDescData)
	})
	return file_sdk_client_clientserver_proto_rawDescData
}

var file_sdk_client_clientserver_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_sdk_client_clientserver_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_sdk_client_clientserver_proto_goTypes = []interface{}{
	(MsgType)(0),         // 0: api.clientserver.v1.MsgType
	(*Message)(nil),      // 1: api.clientserver.v1.Message
	(*MsgHeartBeat)(nil), // 2: api.clientserver.v1.MsgHeartBeat
	(*MsgLoginReq)(nil),  // 3: api.clientserver.v1.MsgLoginReq
	(*MsgLoginResp)(nil), // 4: api.clientserver.v1.MsgLoginResp
	(*MsgQueueInfo)(nil), // 5: api.clientserver.v1.MsgQueueInfo
}
var file_sdk_client_clientserver_proto_depIdxs = []int32{
	0, // 0: api.clientserver.v1.Message.msgID:type_name -> api.clientserver.v1.MsgType
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_sdk_client_clientserver_proto_init() }
func file_sdk_client_clientserver_proto_init() {
	if File_sdk_client_clientserver_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_sdk_client_clientserver_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Message); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sdk_client_clientserver_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MsgHeartBeat); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sdk_client_clientserver_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MsgLoginReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sdk_client_clientserver_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MsgLoginResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sdk_client_clientserver_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MsgQueueInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_sdk_client_clientserver_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_sdk_client_clientserver_proto_goTypes,
		DependencyIndexes: file_sdk_client_clientserver_proto_depIdxs,
		EnumInfos:         file_sdk_client_clientserver_proto_enumTypes,
		MessageInfos:      file_sdk_client_clientserver_proto_msgTypes,
	}.Build()
	File_sdk_client_clientserver_proto = out.File
	file_sdk_client_clientserver_proto_rawDesc = nil
	file_sdk_client_clientserver_proto_goTypes = nil
	file_sdk_client_clientserver_proto_depIdxs = nil
}
